### ISSUE TITLE
Geotagging items on map is slightly off

### ISSUE THREAD

**Issue by swnymor** [horizon-institute/placebooks#111]
When you geotag items to the map, the lon/lat is slightly off by a few metres. e.g the nottingham library marker will show up where the business school is located.

**Comment by ktg** [comment]
I'm sorry, I can't replicate this. I've tried move an item on the map in the editor and taking that lat/lon and sticking it into Open Street Map, Google Maps and Bing Maps. All of them give the same position as the editor.

**Comment by ktg** [comment]
This issue is duplicated in #113.
