### ISSUE TITLE
Geotagged markers are slightly off

### ISSUE THREAD

**Issue by stuaart** [horizon-institute/placebooks#113]
When testing placebooks the other week, I discovered that when you manually geotag items on the map, the lon/lat values that are saved in the XML files are slightly off from where they should be.

log in as me using:
username: markdavies_@hotmail.com
password: test

drag on a map and zoom into the jubilee campus. Geotag something to one of the buildings, download the package and inspect the lon/lat values for that geotagged item, copy/paste the lon/lat values into google maps and notice the difference - it will be off from where it should be. When I tested this, the nottingham library marker was plotted where the business school is located.

**Comment by ktg** [comment]
Checked the editor for this. I've tried move an item on the map in the editor and taking the lat/lon in the json and sticking it into Open Street Map, Google Maps and Bing Maps. All of them give the same position as the editor.

**Comment by stuaart** [comment]
I can't reproduce this problem - the geometry of the image I placed on the map matches the geometry of the stuff I get out in the packaged XML...
