### ISSUE TITLE
Check sharing is working correctly - editor view

### ISSUE THREAD

**Issue by stuaart** [horizon-institute/placebooks#46]
Update: at the moment even though the permissions are being set correctly serverside, it is possible to edit a placebook even if you have r-only access. It is also possible to modify permissions if you have r-only acces.

Same as server issue - check the correct stuff is being reflected in interface.

15.20 logged – Tried to add 2 other users for R+W permissions, appears as read only in feedback box – share works OK ??? – tested AZC/SR not sure now Re Test when security sorted.

**Comment by ktg** [comment]
Fixed display so list now correctly shows 'Read + Write' when permissions are R_W.

**Comment by ktg** [comment]
Shared books appear in my library with original author name under them.
