### ISSUE TITLE
General media download (Everytrail, PCW) issue: hash is null but path is not null

### ISSUE THREAD

**Issue by Alanzc** [horizon-institute/placebooks#67]
Renamed from: Palette thumbnails not appearing on PCW account.

This is potentially when there are multiple imports (by multiple users) of the same external service. Am investigating.

**Comment by stuaart** [comment]
I can't recreate this.

**Comment by Alanzc** [comment]
And I can't get my PCW account to appear, can't press the button to sync. Not sure if it's synching or not, could be a bandwidth thing

**Comment by stuaart** [comment]
I've had a lot of issues with syncing your PCW account too. To me it looks like their servers being rubbish---there is nothing seemingly `bad' happening our end. Everytrail seems very reliable and works every time.

**Comment by Alanzc** [comment]
PCW web site very very slow

**Comment by stuaart** [comment]
Slowness might be related to the fact it is a virtual host and / or tomcat instances starting and stopping.
