### ISSUE TITLE
Audio import from PCW does not work

### ISSUE THREAD

**Issue by stuaart** [horizon-institute/placebooks#71]

**Comment by Alanzc** [comment]
This might be at their end, I looked at it on my trail here http://www.peoplescollectionwales.co.uk/Trail/791-poppit-sands and I don't think the item works. When it loads, something not right about the time it takes to load

**Comment by stuaart** [comment]
Can you make some Peoples Collection content with definitely working media of each type for testing?

**Comment by Alanzc** [comment]
Actually I'll ask them for examples of all media types - I can do it, but I suspect there will be the same issues as the last one I did.

**Comment by stuaart** [comment]
The question is, Alan, how much time we spend on their issues. Given the limited time and man power in my view we should firm up the editor and webapp.
