### ISSUE TITLE
Deleting Published Books

### ISSUE THREAD

**Issue by swnymor** [horizon-institute/placebooks#8]
Unable to delete "ynyslas birds" , book id 23666

username: ynyslas@ccw.gov.uk
password: ynyslas@ynyslas

When I click Actions->Delete Placebook... nothing happens

**Comment by MarkPaxton** [comment]
Confirmed this on placebooks.org
Can't test on dev version due to issue 10 https://github.com/horizon-institute/Bridging-the-Rural-Divide--Placebooks/issues/10

**Comment by ktg** [comment]
Fixed
